BOX = "bento/ubuntu-16.04"
BOX_VERSION = "2.3.8"

Vagrant.configure("2") do |config|

  config.vm.define "gw" do |d|
    d.vm.box = BOX
    d.vm.box_version = BOX_VERSION
    d.vm.box_check_update = false
    d.vm.hostname = "gw"
    d.vm.network "private_network", ip: "10.0.0.41"
    d.vm.network "private_network", ip: "10.0.1.41"
    d.vm.network "private_network", ip: "10.0.3.41"
    d.vm.network "private_network", ip: "10.0.4.41"
    d.vm.provider "virtualbox" do |p|
      p.cpus = "1"
      p.memory = "512"
      p.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      p.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
      p.customize ["modifyvm", :id, "--nicpromisc4", "allow-all"]
      p.customize ["modifyvm", :id, "--nicpromisc5", "allow-all"]
    end
    d.vm.provision "bootstrap", type: "shell", path: "bootstrap-gw.sh", args: ["download", "configure"]
    d.vm.provision "download", type: "shell", path: "bootstrap-gw.sh", args: ["download"]
    d.vm.provision "configure", type: "shell", path: "bootstrap-gw.sh", args: ["configure"]
    d.vm.provision "update", type: "shell", path: "update-gw.sh", run: "never"
  end

  config.vm.define "gw-client" do |d|
    d.vm.box = BOX
    d.vm.box_version = BOX_VERSION
    d.vm.box_check_update = false
    d.vm.hostname = "gw-client"
    d.vm.network "private_network", ip: "10.0.0.42"
    d.vm.network "private_network", ip: "10.0.1.42"
    d.vm.network "private_network", ip: "10.0.3.42"
    d.vm.network "private_network", ip: "10.0.4.42"
    d.vm.provider "virtualbox" do |p|
      p.cpus = "1"
      p.memory = "512"
      p.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      p.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
      p.customize ["modifyvm", :id, "--nicpromisc4", "allow-all"]
      p.customize ["modifyvm", :id, "--nicpromisc5", "allow-all"]
    end
    d.vm.provision "bootstrap", type: "shell", path: "bootstrap-gw-client.sh", args: ["download", "configure"]
    d.vm.provision "download", type: "shell", path: "bootstrap-gw-client.sh", args: ["download"]
    d.vm.provision "configure", type: "shell", path: "bootstrap-gw-client.sh", args: ["configure"]
    d.vm.provision "update", type: "shell", path: "update-gw-client.sh", run: "never"
  end

end
