# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.2"
  config.vm.box_version = "2.3.1"
  config.vm.box_check_update = false
  config.vm.hostname = "os-kolla"

  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "bootstrap", type: "shell", inline: <<-SHELL
    # Update /etc/hosts
    echo "10.0.2.15 os-kolla" >> /etc/hosts
    
    yum update -y
 
    # Install pip
    yum install -y epel-release
    yum install -y python-pip
    pip install -U pip

    # Install ansible
    yum install -y python-devel libffi-devel gcc openssl-devel
    yum install -y ansible
    pip install -U ansible
    ansible --version # 2.4.2.0

    # Install docker
    curl -sSL https://get.docker.io | bash
    docker --version # 17.12.0-ce

    # Register docker-engine in systemd
    mkdir -p /etc/systemd/system/docker.service.d
    tee /etc/systemd/system/docker.service.d/kolla.conf <<-'EOF'
[Service]
MountFlags=shared
ExecStart=
ExecStart=/usr/bin/dockerd
EOF
    systemctl daemon-reload
    systemctl restart docker

    # Install docker-py
    yum install -y python-docker-py
    pip install -U docker-py # 1.10.6

    # Install ntp
    yum install -y ntp
    systemctl enable ntpd.service
    systemctl start ntpd.service
    ntpq -p

    # Stop libvirtd if exists
    #systemctl stop libvirtd.service
    #systemctl disable libvirtd.service

    # =================================

    # Install kolla-ansible
    pip install kolla-ansible # 5.0.1

    # Copy globals.yml and passwords.yml to /etc/kolla/
    cp -r /usr/share/kolla-ansible/etc_examples/kolla /etc/kolla/
  
    # Copy the inventory file to the current directory
    cp /usr/share/kolla-ansible/ansible/inventory/* .

    # To configure the interface, edit /etc/kolla/globals.yml
    sed -i 's/^#network_interface: "eth0"$/network_interface: "eth0"/' /etc/kolla/globals.yml
    sed -i 's/^#neutron_external_interface: "eth1"$/neutron_external_interface: "eth1"/' /etc/kolla/globals.yml

    # Generate the password using kolla-genpwd. Results are saved in /etc/kolla/passwords.yml
    kolla-genpwd

    # To quickly prepare hosts, playbook bootstrap-servers can be used.
    kolla-ansible -i all-in-one bootstrap-servers # TODO failed : overwrite my /etc/systemd/system/docker.service.d/kolla.conf !!!

    # =================================

    # Pull the Docker image
    kolla-ansible pull # TODO
 
  SHELL
end
